sudo: required

services:
- docker


script:
- echo"hello"

after_success:
-docker build -t aartijagtap/zomato-master-client ./client
-docker build -t aartijagtap/zomato-master-server ./server
-docker build -t aartijagtap/zomato-master-nginx ./nginx

-echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


-docker push aartijagtap/zomato-master-client ./client
-docker push aartijagtap/zomato-master-server ./server
-docker push aartijagtap/zomato-master-nginx ./nginx